### ISSUE TITLE
Homework Week 11

### ISSUE THREAD

**Issue by ptums** [ltdelia/studentsOnTheBus#1]
Hey Lou, awesome job on the homework! I ran through your code and it looks like everything works properly and you were success in making a constructor function and using node to import scripts. WHat was your big take away from this assignment?

**Comment by ltdelia** [comment]
Hi Peter! In retrospect, I was not successful at getting several features to function in the app:
- Adding 20 students to the newly created bus object
- Defining the busChatter function to access the catchPhrase for each student
- Calling the busChatter function

Aside from the above, my big takeaway was understanding how to use constructor functions, and how to properly reference files/objects in the appropriate files.
